Address 관련 작업 및 테스트 작성
TravelCompass-UMC/Backend pull request #13
Opened 2024-01-09 06:49 UTC by HxWOO

#11  PR 타입
- 기능 추가

### 반영 브랜치
feature/11 -> develop

### 변경 사항
Address  관련 사항 service단까지 추가하고 테스트 실행했습니다.

### 테스트 결과
- 단위 테스트
<img width="574" alt="image" src="https://github.com/TravelCompass-UMC/Backend/assets/128457220/ecd90b4a-4174-4d58-8b23-831383062f1f">
- 통합 테스트 
<img width="629" alt="image" src="https://github.com/TravelCompass-UMC/Backend/assets/128457220/e895bb60-42a8-4761-bb3f-8a53a25a26c5">

#11

2024-01-09 07:17 UTC, Enble requested changes
법정동 코드를 db로 가져오는 부분도 작성 부탁해!

2024-01-09 07:17 UTC, Enble commented on src/main/java/com/travelcompass/api/adress/service/AddressService.java
> +                () -> new GeneralException(ErrorCode.ADDRESS_NOT_FOUND)
내가 깜빡하고 GeneralException 생성자를 private으로 안해놨었네... 정적 팩토리 메서드 사용하도록 바꾸면 좋을 것 같아!

2024-01-09 07:17 UTC, Enble commented on src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
> +    ADDRESS_NOT_FOUND(HttpStatus.NOT_FOUND, "Address_404", "주소를 찾을 수 없습니다.")
code 부분을 위의 COMMON_400처럼 대문자로 하던가, 아니면 Common_404처럼 하던가 같이 통일해서 작성하면 좋을 것 같아.

2024-01-09 07:29 UTC, HxWOO commented on src/main/java/com/travelcompass/api/adress/service/AddressService.java
> +                () -> new GeneralException(ErrorCode.ADDRESS_NOT_FOUND)
아.. 확인했어!!

2024-01-09 07:29 UTC, HxWOO commented on src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
> +    ADDRESS_NOT_FOUND(HttpStatus.NOT_FOUND, "Address_404", "주소를 찾을 수 없습니다.")
확인확인!

2024-01-10 09:42 UTC, persi0815 approved these changes

2024-01-10 10:37 UTC, Enble commented
아직 작업중인 PR일 때는 [WIP] 넣어서 제목 수정 해줘~

2024-01-11 09:21 UTC, Enble approved these changes
LGTM

2024-01-11 09:21 UTC, merged