Feature/19
TravelCompass-UMC/Backend pull request #24
Opened 2024-01-19 09:25 UTC by HxWOO

### PR 타입
- 기능 추가

### 반영 브랜치
feature/19 -> develop

### 변경 사항
- plan 관련 엔티티 추가 및 테스트 코드 작성

### 테스트 결과
- 도메인 테스트 결과
  
<img width="657" alt="image" src="https://github.com/TravelCompass-UMC/Backend/assets/128457220/77748fe6-17ed-417a-85e6-84d2b4d7f11f">

2024-01-19 09:37 UTC, Enble requested changes

2024-01-19 09:37 UTC, Enble commented on src/main/java/com/travelcompass/api/plan/domain/Plan.java
> +    @ManyToOne(fetch = FetchType.LAZY)
JoinColumn 사용해서 컬럼 직접 지정해줘

2024-01-19 09:37 UTC, Enble commented on src/main/java/com/travelcompass/api/plan/domain/PlanGroup.java
> +    @ManyToOne(fetch = FetchType.LAZY)
얘네들도 joincolumn 부탁해

2024-01-19 11:47 UTC, HxWOO commented on src/main/java/com/travelcompass/api/plan/domain/Plan.java
> +    @ManyToOne(fetch = FetchType.LAZY)
알았으

2024-01-20 17:22 UTC, Enble approved these changes
LGTM

2024-01-21 05:14 UTC, merged