[wip][#35] 여행계획 관련 API 개발
TravelCompass-UMC/Backend pull request #41
Opened 2024-01-26 12:37 UTC by HxWOO

### PR 타입
- 기능 추가

### 반영 브랜치
- feature/35 -> develop

### 변경 사항
- 여행계획 생성, 수정, 초대, 특정계획 조회 기능 개발

### 테스트 결과
- 
<img width="1285" alt="image" src="https://github.com/TravelCompass-UMC/Backend/assets/128457220/a3bf4068-2f24-4730-80d9-e8911415b729">

2024-01-26 12:41 UTC, Enble commented on src/main/java/com/travelcompass/api/hashtag/service/HashtagService.java
> +        List<Hashtag> newHashtags = tags.stream()
깔끔하게 스트림으로 떨어지는 로직 좋네. 굿굿!

2024-01-26 12:48 UTC, Enble requested changes

2024-01-26 12:48 UTC, Enble commented on src/main/java/com/travelcompass/api/plan/service/PlanService.java
> +    public Plan createPlan(PlanReqDto requestDto, User user){
이거 Transactional 안붙이면 안돌아갈 것 같은데?

2024-01-26 12:48 UTC, Enble commented on src/main/java/com/travelcompass/api/plan/service/PlanService.java
> +    public Plan createPlan(PlanReqDto requestDto, User user){
아래 다른 CUD 로직도 비슷할 것 같아.

2024-01-26 12:48 UTC, Enble commented on src/main/java/com/travelcompass/api/plan/domain/Plan.java
> +    public void updateHits(Long hits) {
개인적으로 이렇게 하는 것도 나쁘지 않은데, 그냥 this.hits++은 애매할까? 어떻게 생각하는지 궁금해

2024-01-26 12:48 UTC, Enble commented on src/main/java/com/travelcompass/api/plan/controller/PlanController.java
> +public class PlanController {
조금 귀찮을 수도 있는데, 서비스쪽 수정 끝나면 포스트맨으로 한번씩만 테스트 부탁해.

2024-01-26 12:53 UTC, HxWOO commented on src/main/java/com/travelcompass/api/plan/service/PlanService.java
> +    public Plan createPlan(PlanReqDto requestDto, User user){
아 맞다
확인 확인

2024-01-26 13:10 UTC, HxWOO commented on src/main/java/com/travelcompass/api/plan/controller/PlanController.java
> +public class PlanController {
당근이징

2024-01-26 13:10 UTC, HxWOO commented on src/main/java/com/travelcompass/api/plan/domain/Plan.java
> +    public void updateHits(Long hits) {
근데 그러면 viewCount 디비에 있는 숫자랑 안 맞을 수 있을거 같아서

2024-01-27 03:49 UTC, Enble commented on src/main/java/com/travelcompass/api/plan/domain/Plan.java
> +    public void updateHits(Long hits) {
오케이 굿굿

2024-01-30 07:30 UTC, persi0815 approved these changes

2024-01-30 10:00 UTC, Enble approved these changes
LGTM

2024-01-30 10:03 UTC, merged